### ISSUE TITLE
New standard for calls.

### ISSUE THREAD

**Issue by jsds96** [salesforce-marketingcloud/postman#6]
Could you please build a new document following the new standards for calling?

**Comment by StefAtPollinate** [comment]
I would like to add to this request. The auth request I was trying to make using the code here lacks the grant_type and the account_id properties in the Body. 

I see that in the [pull request](https://github.com/salesforce-marketingcloud/postman/pull/9) that this repo will be changed to Community Supported. If that's the case, can that pull be merged so that people can start fixing this repo to current standards?

**Comment by acates1982** [comment]
Collection has been updated.
